name: 'Github Release Changelog Generator'
author: 'Kenny Wong'
description: 'Returns the commit difference count between two git references.'
inputs:
  token:
    description: 'Your GITHUB_TOKEN'
    default: ''
    required: true
  filter:
    description: 'Regular expression filtering'
    default: ''
    required: false
  filter-author:
    description: 'Regular expression filtering'
    default: ''
    required: false
  head-ref:
    description: 'The name of the head reference'
    default: ''
    required: false
  base-ref:
    description: 'The name of the base reference'
    default: ''
    required: false

outputs:
  version:
    description: 'The version number of the tag created. example: 1.0.0'
  changelog:
    description: 'Markdown formatted changelog'
  compareurl:
    description: 'Comparing two branches to see what’s changed or to start a new pull request.'
  tag:
    description: 'Tag name.'
  branch:
    description: 'Branch name.'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'list'
  color: 'blue'
