name: 'Get a changelog between two references'
author: 'Kenny Wong'
description: 'Returns the commit difference count between two git references.'
inputs:
  mytoken:
    description: 'Your GITHUB_TOKEN'
    default: ''
    required: true
  head-ref:
    description: 'The name of the head reference'
    default: ''
    required: false
  base-ref:
    description: 'The name of the base reference'
    default: ''
    required: false
outputs:
  changelog:
    description: 'Markdown formatted changelog'
  compareurl:
    description: 'Comparing two branches to see what’s changed or to start a new pull request.'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'list'
  color: 'blue'
