name: test
on: [push]

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate changelog
        id: changelog
        uses: jaywcjlove/changelog-generator@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filter-author: (jaywcjlove|小弟调调™|dependabot\[bot\]|Renovate Bot)
          filter: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'

      - name: Get the tag name
        run: echo "${{ steps.changelog.outputs.tag }}"

      - name: Get the branch name
        run: echo "${{ steps.changelog.outputs.branch }}"

      - name: Get comparing changes url,
        run: echo "${{ steps.changelog.outputs.compareurl }}"

      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: |
            ${{ steps.changelog.outputs.compareurl }}
            ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false