name: test
on: [push]

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - run: npm install
      - run: npm run build

      - run: mkdir -p build
      - run: npm i markdown-to-html-cli -g
      - run: markdown-to-html --output build/index.html --github-corners https://github.com/jaywcjlove/changelog-generator

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build

      - name: Create Tag
        id: create_tag
        uses: jaywcjlove/create-tag-action@v1.3.6
        with:
          package-path: ./package.json

      - name: Generate Changelog
        id: changelog
        # uses: jaywcjlove/changelog-generator@main
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          head-ref: ${{steps.create_tag.outputs.version}}
          original-markdown: true
          filter: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'

      - run: echo "outputs.tag - ${{ steps.changelog.outputs.tag }}"
      - run: echo "outputs.branch - ${{ steps.changelog.outputs.branch }}"
      - run: echo "outputs.compareurl - ${{ steps.changelog.outputs.compareurl }}"
      - run: echo "outputs.version - ${{ steps.changelog.outputs.version }}"
      - run: echo "outputs.gh-pages-hash - ${{ steps.changelog.outputs['gh-pages-hash'] }}"

      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        # if: startsWith(github.ref, 'refs/tags/')
        if: steps.create_tag.outputs.successful
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.create_tag.outputs.version }}
          release_name: ${{ steps.create_tag.outputs.version }}
          body: |
            ```yml
            - name: Generate changelog
              id: changelog
              uses: jaywcjlove/changelog-generator@${{ steps.create_tag.outputs.version }}
              with:
                token: # Your GITHUB_TOKEN
                filter-author: (jaywcjlove|小弟调调™|dependabot\[bot\]|Renovate Bot)
                filter: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'
            ```
            
            ${{ steps.changelog.outputs.compareurl }}
            
            ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false
