name: test
on: [push]

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate changelog
        id: changelog
        uses: jaywcjlove/changelog-generator@main
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Get the changelog
        run: echo "${{ steps.changelog.outputs.changelog }}"

      - name: Get comparing changes url,
        run: echo "${{ steps.changelog.outputs.compareurl }}"